# Generated by Django 6.0.1 on 2026-02-03 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_content', models.TextField()),
                ('background_image', models.URLField(blank=True, null=True)),
                ('trust_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('trust_level_change', models.IntegerField(default=0)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.scene')),
            ],
        ),
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='game.story'),
        ),
        migrations.CreateModel(
            name='PlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.scene')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.story')),
            ],
        ),
    ]
