# Generated by Django 6.0.1 on 2026-02-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='trust_level',
            field=models.IntegerField(unique=True),
        ),
    ]
