# Generated by Django 6.0.1 on 2026-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_scene_trust_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='trust_level',
            field=models.IntegerField(default=0),
        ),
    ]
