# Generated by Django 6.0.1 on 2026-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_scene_trust_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_ending',
            field=models.BooleanField(default=False),
        ),
    ]
