# Generated by Django 6.0.1 on 2026-02-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_scene_is_ending'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_starting',
            field=models.BooleanField(default=False),
        ),
    ]
